name: Build and push images

on:
  push:
    branches: ["*"]
    paths:
    - src/**/.devcontainer/Dockerfile
    - src/**/.devcontainer/devcontainer*.json
    - src/**/.devcontainer/local-features/**
    - scripts/dc-builder
    - .github/workflows/docker-builds.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - src: debian
            name: base/debian
    permissions:
      contents: read
      packages: write
    steps:
    - name: Clean runner for Docker builds
      uses: sctg-development/clean-image-for-docker@v1
      with:
        remove-development-tools: 'true'
        remove-browsers: 'true'
        remove-databases: 'true'
        remove-cloud-tools: 'true'
        show-top-packages: 'true'
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install Dev Containers CLI
      run: npm i -g @devcontainers/cli
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: "true"
        driver-opts: image=moby/buildkit:latest
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      run: ./scripts/dc-builder ${{ matrix.image.src }} ${{ matrix.image.name }}
      env:
        FF_DEVCONTAINER_SKIP_PUSH: ${{ github.event_name == 'pull_request' }}